'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('tiler', {
  onApplyLayout: (cb) => ipcRenderer.on('apply-layout', (_e, data) => cb(data)),
  videoEnded: (instanceId) => ipcRenderer.send('video-ended', { instanceId }),
  rendererReady: () => ipcRenderer.send('renderer-ready'),
  forceNext: () => ipcRenderer.send('force-next'),
  insertVideo: (side, kind) => ipcRenderer.send('insert-video', { side, kind }),
  removeTile: (instanceId) => ipcRenderer.send('remove-tile', { instanceId }),
  swapTile: (instanceId) => ipcRenderer.send('swap-tile', { instanceId }),
  previousTile: (instanceId) => ipcRenderer.send('previous-tile', { instanceId }),
  onSwapTile: (cb) => ipcRenderer.on('swap-tile', (_e, d) => cb(d)),
  onPreviousResult: (cb) => ipcRenderer.on('previous-result', (_e, d) => cb(d)),
  swapTilePositions: (aId, bId) => ipcRenderer.send('swap-tile-positions', { aId, bId }),
  folderPref: (folder, want) => ipcRenderer.send('folder-pref', { folder, want }),
  onPrefResult: (cb) => ipcRenderer.on('pref-result', (_e, d) => cb(d)),
  onPrefLevels: (cb) => ipcRenderer.on('pref-levels', (_e, d) => cb(d)),
  setVolume: (volume) => ipcRenderer.send('set-volume', { volume }),
  onVolume: (cb) => ipcRenderer.on('volume', (_e, d) => cb(d)),
  onPlayerConfig: (cb) => ipcRenderer.on('player-config', (_e, d) => cb(d)),
  onRecordConfig: (cb) => ipcRenderer.on('record-config', (_e, d) => cb(d)),
  onRecordStop: (cb) => ipcRenderer.on('record-stop', (_e, d) => cb(d)),
  recordOpen: (kind, ext) => ipcRenderer.invoke('record-open', { kind, ext }),
  recordChunk: (id, data) => ipcRenderer.send('record-chunk', { id, data }),
  recordClose: (id, note) => ipcRenderer.send('record-close', { id, note }),
  onBreathingSchedule: (cb) => ipcRenderer.on('breathing-schedule', (_e, d) => cb(d)),
  onBreathingStart: (cb) => ipcRenderer.on('breathing-start', (_e, d) => cb(d)),
  onBreathingEnd: (cb) => ipcRenderer.on('breathing-end', (_e, d) => cb(d)),
  breathingSkip: () => ipcRenderer.send('breathing-skip'),
  breathingNow: () => ipcRenderer.send('breathing-now'),
  onCountdownPos: (cb) => ipcRenderer.on('countdown-pos', (_e, d) => cb(d)),
  countdownSet: (x, y, height) => ipcRenderer.send('countdown-set', { x, y, height }),
  onTempo: (cb) => ipcRenderer.on('tempo', (_e, d) => cb(d)),
  onRhythm: (cb) => ipcRenderer.on('rhythm', (_e, d) => cb(d)),
  rhythmToggle: () => ipcRenderer.send('rhythm-toggle'),
  tapTempo: () => ipcRenderer.send('tap-tempo'),
  onHypno: (cb) => ipcRenderer.on('hypno', (_e, d) => cb(d)),
  hypnoToggle: () => ipcRenderer.send('hypno-toggle'),
  hypnoCycle: () => ipcRenderer.send('hypno-cycle'),
  onTextOverlay: (cb) => ipcRenderer.on('text-overlay', (_e, d) => cb(d)),
  textToggle: () => ipcRenderer.send('text-toggle'),
  onAffirmation: (cb) => ipcRenderer.on('affirmation', (_e, d) => cb(d)),
  onNarration: (cb) => ipcRenderer.on('narration', (_e, d) => cb(d)),
  onDuck: (cb) => ipcRenderer.on('duck', (_e, d) => cb(d)),
  onGoal: (cb) => ipcRenderer.on('goal', (_e, d) => cb(d)),
  markClimax: () => ipcRenderer.send('mark-climax'),
  onClimaxRecorded: (cb) => ipcRenderer.on('climax-recorded', (_e, d) => cb(d)),
  reshuffle: () => ipcRenderer.send('reshuffle'),
  openControls: () => ipcRenderer.send('open-controls'),
  quit: () => ipcRenderer.send('quit'),
  log: (msg) => ipcRenderer.send('renderer-log', msg),
});
